version: '2.0'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3326:3306"
    environment:
      MYSQL_ROOT_PASSWORD: r00t

  exchange:
    image: stocktrade/exchange:latest
    ports:
      - "8888:8080"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: 192.168.2.10
      MYSQL_PORT: 3326
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: r00t
      SPRING_PROFILES_ACTIVE: dev
