
exchangeURL: ${EXCHANGE_URL}
traderId: ${TRADER_ID}

spring:
  profiles: dev
  application:
    name: trader
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/trader
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URL}
          jwk-set-uri: ${JWT_ISSUER_URL}/protocol/openid-connect/certs

