
exchangeURL: ${EXCHANGE_URL}
traderId: ${TRADER_ID}

server:
  servlet:
    context-path: /quicktrade

spring:
  profiles: dev
  application:
    name: trader
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/trader
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/frankrealm
          jwk-set-uri: http://localhost:8080/auth/realms/frankrealm/protocol/openid-connect/certs

